 
# CI Pipeline with Security Tools + Artifact Registry Push

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  dynamicSubstitutions: true

substitutions:
  _FRONTEND_IMAGE: "frontend-app"
  _BACKEND_IMAGE: "backend-app"
  _REGION: "us-east1"
  _REPO: "passop-repo"            # Artifact Registry repository

steps:

 
# 1. Install Security Tools
 
- name: "gcr.io/cloud-builders/npm"
  id: "Install Dependencies"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      cd backend && npm install
      cd ../frontend && npm install

 
# 3. Build Docker Images 
 
- name: "gcr.io/cloud-builders/docker"
  id: "Build Frontend Image"
  args:
    [
      "build",
      "-t",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_FRONTEND_IMAGE:$COMMIT_SHA",
      "./frontend"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: "Build Backend Image"
  args:
    [
      "build",
      "-t",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA",
      "./backend"
    ]

 
# 4. Security Scan Docker Images
 
# **Security Tool 7: Trivy Image Scan**
- name: "aquasec/trivy"
  id: "Trivy Image Scan"
  entrypoint: bash
  args:
    - "-c"
    - |
      trivy image --severity HIGH,CRITICAL $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_FRONTEND_IMAGE:$COMMIT_SHA
      trivy image --severity HIGH,CRITICAL $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA

 
# 5. Push to Artifact Registry
 
- name: "gcr.io/cloud-builders/docker"
  id: "Push Frontend Image"
  args:
    [
      "push",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_FRONTEND_IMAGE:$COMMIT_SHA"
    ]

- name: "gcr.io/cloud-builders/docker"
  id: "Push Backend Image"
  args:
    [
      "push",
      "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA"
    ]

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_FRONTEND_IMAGE:$COMMIT_SHA"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA"

timeout: "1200s"
